### ISSUE TITLE
CSS @import Breaks Linting

### ISSUE THREAD

**Issue by Briles** [FichteFoll/SublimeLinter-contrib-sublime-syntax#2]
On Windows 10 with ST v3109 when the linter encounters the CSS `import` at-rule, the import at-rule meta scope becomes the scope all following assertions are tested against.

Take the following example:

``` css
    @import;    /* meta.at-rule.import.css */

    html {}    /* correctly scoped as entity.name.tag.css */
/*  ^^^^ entity.name.tag.css */
```

The resulting output is:

```
[entity.name.tag.css] does not match scope [source.css meta.at-rule.import.css]
[entity.name.tag.css] does not match scope [source.css meta.at-rule.import.css]
[entity.name.tag.css] does not match scope [source.css meta.at-rule.import.css]
[entity.name.tag.css] does not match scope [source.css meta.at-rule.import.css]
```

**Comment by FichteFoll** [comment]
Is this replicable when running the default build system for syntax tests?

**Comment by Briles** [comment]
Everything works OK when running the default build system; all assertions pass.

**Comment by Briles** [comment]
Seems it may have something to do with the combination of `@import` and the semicolon `;`

``` css
    @import;    /* does not work */
    import;     /* works */
    @import     /* works */
    @;          /* works */
```

**Comment by FichteFoll** [comment]
That's odd. I get all the failures from `CSS/syntax_test_css.css` from Sublime Text's build system as well, which is expected. Only if I unextract the file however, not if it's read from `CSS.sublime-package`. I explicitly set the line endings to UNIX style too, which is a bug in the syntax test runner to be fixed with 3112, but the results didn't change.

Other than that, besides the fact that the line

``` css
@import "x" print;
```

breaks all following assertions due to some seemingly unclosed `meta.at-rule.import` scope, I'm at a loss at why this happens in certain circumstances only. I'd like to wait for the release of 3112 and see if that miraculously fixes it and otherwise investigate `CSS.sublime-syntax` for potential bugs in the syntax test runner.

**Comment by Briles** [comment]
This seems to have been miraculously fixed in 3112

**Comment by FichteFoll** [comment]
Let's just assume this was an issue related to https://github.com/SublimeTextIssues/Core/issues/963 then.
